### ISSUE TITLE
правки рк3

### ISSUE THREAD

**Issue by NikitaKot1** [xanderkov/ics7-exams#1]
вопрос 1: в свойстве 5 предел x->x0-
вопрос 2: -inf в пределе в определении
вопрос 3: в свойстве 2 -- не нужно <=, лучше сравнение с пунктиров
вопрос 4: в определении 1 не xi, а Xi
вопрос 4: в определении 2 сравнение 1 должно быть строгим
вопрос 5: пусть, пункт 2 -- X до xm, а не xn
вопрос 5: в таблице Py, а не py
вопрос 5: в последнем интегрировании xn, а не xn1\
вопрос 6: свойство 7 с -inf
вопрос 6: свойство 3 -- R^2
вопрос 7: свойство 5 -- маргинальные плотности
вопрос 13: замечание к дискретной СВ че за дичь с схождением
вопрос 13: свойство 1
вопрос 15: в квантили нужен 1 - alfa

**Comment by xanderkov** [comment]
Пошел нахуй, я бог, а ты лох

**Comment by NikitaKot1** [comment]
ты ничто без папочки Власова

**Comment by xanderkov** [comment]
АААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААА
